FROM python:3.10-slim

WORKDIR /app
COPY requirements.txt requirements-dev.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
RUN python -m database.seed.seed_database

EXPOSE 8000
CMD ["python", "-m", "backend.run_api"]
